apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadiyaproductsapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hadiyaproductsapi
  template:
    metadata:
      labels:
        app: hadiyaproductsapi
    spec:
      containers:
      - name: hadiyaproductsapi
        image: hadiyaproductsapi:latest
        ports:
        - containerPort: 3000
