apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadiyaproductsapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hadiyaproductsapi
  template:
    metadata:
      labels:
        app: hadiyaproductsapi
    spec:
      containers:
      - name: hadiyaproductsapi
        image: sankalpmt/hadiyaproductsapi:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: hadiyaproductsapi-service
spec:
  type: LoadBalancer
  selector:
    app: hadiyaproductsapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

