apiVersion: v1
kind: Service
metadata:
  name: hadiyaproductsapi-service
spec:
  type: NodePort
  selector:
    app: hadiyaproductsapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
